name: run main.py

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs: 
  on_start:
    runs-on: fedora-latest
  
    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5
  
  
      # In README.md, switch step 0 for step 1.
      - name: Update to step 1
        uses: skills/action-update-step@v2
        with:
          python-version: '3.11' # install the python version need
